poses:
  - pose_1:
      position_x: 66358.2890625
      position_y: 42480.4765625
      position_z: 0.0
      orientation_x: 0.0
      orientation_y: 0.0
      orientation_z: 0.04496333854008627
      orientation_w: 0.9989886376667803
  - pose_2:
      position_x: 66290.4375
      position_y: 42425.66796875
      position_z: 30.2772
      orientation_x: 0.0
      orientation_y: 0.0
      orientation_z: 1.0
      orientation_w: 6.123233995736766e-17
returnPoint:
  position_x: 66271.3359375
  position_y: 42482.56640625
  position_z: 30.8577
  orientation_x: 0.0
  orientation_y: 0.0
  orientation_z: 0.0
  orientation_w: 1.0